Parameters:
  KeyPair:
    Description: KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  SNSEndpointMail:
    Description: SNSEndpointMail
    Type: String
  StacksBucketName:
    Description: Bucket Name for the Cloudformation Stacks
    Type: String
  CloudTrailBucketName:
    Description: Bucket Name for the CloudTrail
    Type: String
  ArtifactsBucketName:
    Description: Bucket Name for Artifacts Stages Transitions
    Type: String
  CodeCommitRepoName:
    Description: CodeCommit Repo Name
    Type: String
  ECRRepoName:
    Description: ECR Repo Name
    Type: String

Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/01_IAM.yml
  SNS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/02_SNS.yml
      Parameters:
        Endpoint: !Ref SNSEndpointMail
  Storage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/03_Storage.yml
      Parameters:
        CloudTrailBucketName: !Ref CloudTrailBucketName
        ArtifactsBucketName: !Ref ArtifactsBucketName
  CloudWatch:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/04_CloudWatch.yml
  Kinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/05_Kinesis.yml
    DependsOn: [CloudWatch, IAM, Storage]
  CloudWatchSubscriptions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/06_CloudWatchSubscriptions.yml
    DependsOn: [CloudWatch, IAM, Storage, Kinesis]
  SSM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/07_SSM.yml
    DependsOn: [CloudWatch]
  CloudTrail:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/08_CloudTrail.yml
      Parameters:
        CloudTrailBucketName: !Ref CloudTrailBucketName
    DependsOn: [IAM, Storage, CloudWatch]
  Networking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/09_Networking.yml
      Tags:
        - Key: Env
          Value: Dev
    DependsOn: [CloudWatchSubscriptions, CloudTrail]
  Firewalls:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/10_Firewalls.yml
      Tags:
        - Key: Env
          Value: Dev
    DependsOn: [Networking]
  NATInstances:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/11_NATInstances.yml
      Tags:
        - Key: Env
          Value: Dev
      Parameters:
        KeyPair: !Ref KeyPair
    DependsOn: [Networking, Firewalls]
  BastionHost:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/12_BastionHost.yml
      Tags:
        - Key: Env
          Value: Dev
      Parameters:
        PublicSubnet: !GetAtt Networking.Outputs.PublicSubnet1
        KeyPair: !Ref KeyPair
    DependsOn: [Networking, Firewalls]
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/13_ALB.yml
      Tags:
        - Key: Env
          Value: Dev
      Parameters:
        VPC: !GetAtt Networking.Outputs.VPC
        Subnets: !GetAtt Networking.Outputs.PublicSubnets
    DependsOn: [Networking, Firewalls]
  EC2ASG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/14_EC2ASG.yml
      Tags:
        - Key: Env
          Value: Dev
      Parameters:
        Subnets: !GetAtt Networking.Outputs.PrivateSubnets
        KeyPair: !Ref KeyPair
    DependsOn: [ALB, NATInstances, SSM]
  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/15_ECSCluster.yml
      Tags:
        - Key: Env
          Value: Dev
      Parameters:
        Subnets: !GetAtt Networking.Outputs.PrivateSubnets
        KeyPair: !Ref KeyPair
    DependsOn: [ALB, NATInstances, SSM]
  TaskDefinition:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/16_TaskDefinition.yml
      Tags:
        - Key: Env
          Value: Dev
    DependsOn: [ALB, ECSCluster]
  ECSEC2Services:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/17_ECSEC2Services.yml
      Tags:
        - Key: Env
          Value: Dev
      Parameters:
        Subnets: !GetAtt Networking.Outputs.PrivateSubnets
    DependsOn: [ALB, ECSCluster, TaskDefinition]
  ECSFargateServices:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/18_ECSFargateServices.yml
      Tags:
        - Key: Env
          Value: Dev
      Parameters:
        Subnets: !GetAtt Networking.Outputs.PrivateSubnets
    DependsOn: [ALB, ECSCluster, TaskDefinition]
  CodeCommit:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/19_CodeCommit.yml
      Parameters:
        StacksBucketName: !Ref StacksBucketName
        CodeCommitRepoName: !Ref CodeCommitRepoName
    DependsOn: [IAM, CloudTrail]
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/20_ECR.yml
      Parameters:
        ECRRepoName: !Ref ECRRepoName
    DependsOn: [IAM, CloudTrail]
  CodeBuild:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/21_CodeBuild.yml
    DependsOn: [CodeCommit, ECR]
  CodeDeploy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/22_CodeDeploy.yml
    DependsOn: [CodeCommit, ECR, CodeBuild, EC2ASG]
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/23_CodePipeline.yml
      Parameters:
        ArtifactsBucketName: !Ref ArtifactsBucketName
    DependsOn: [CodeCommit, ECR, CodeBuild, CodeDeploy, EC2ASG, ECSEC2Services, ECSFargateServices]
  Inspector:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/24_Inspector.yml
    DependsOn: [CodePipeline]
  DetectDriftedStacksLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/25_DetectDriftedStacksLambda.yml
      Parameters:
        ScanStackName: "Master"
    DependsOn: [CodePipeline, SNS]
  EventBridge:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/26_EventBridge.yml
    DependsOn: [DetectDriftedStacksLambda, SNS]
  DeleteBucketObjectsLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StacksBucketName}.s3.${AWS::Region}.amazonaws.com/27_DeleteBucketObjectsLambda.yml
      Parameters:
        StacksBucketName: !Ref StacksBucketName
        CloudTrailBucketName: !Ref CloudTrailBucketName
        ArtifactsBucketName: !Ref ArtifactsBucketName
    DependsOn: [IAM]

