Parameters:
  CloudTrailBucketName:
    Description: Bucket Name for the CloudTrail
    Type: String
  ArtifactsBucketName:
    Description: Bucket Name for Artifacts Stages Transitions
    Type: String
  VarLogMessagesBucketName:
    Description: Bucket Name for VarLogMessages
    Type: String

Resources:
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      BucketName: !Ref CloudTrailBucketName
  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Statement:
          - Sid: AWSCloudTrailAclCheck20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub "arn:aws:s3:::${CloudTrailBucketName}"
          - Sid: AWSCloudTrailWrite20150319
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${CloudTrailBucketName}/*"
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      BucketName: !Ref ArtifactsBucketName
  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Statement:
          - Sid: AllowEC2Access
            Effect: Allow
            Action: s3:*
            Resource: !Sub "arn:aws:s3:::${ArtifactsBucketName}/*"
            Principal:
              Service: ec2.amazonaws.com
  VarLogMessagesBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256
      BucketName: !Ref VarLogMessagesBucketName
  VarLogMessagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VarLogMessagesBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudTrail
            Effect: Allow
            Action: s3:*
            Resource: !Sub "arn:aws:s3:::${VarLogMessagesBucketName}/*"
            Principal:
              Service: cloudtrail.amazonaws.com


Outputs:
  CloudTrailBucket:
    Description: A reference to the CloudTrailBucket Arn
    Value: !GetAtt CloudTrailBucket.Arn
    Export:
      Name: CloudTrailBucket
  ArtifactsBucket:
    Description: A reference to the ArtifactsBucket Arn
    Value: !GetAtt ArtifactsBucket.Arn
    Export:
      Name: ArtifactsBucket
  VarLogMessagesBucket:
    Description: A reference to the VarLogMessagesBucket Arn
    Value: !GetAtt VarLogMessagesBucket.Arn
    Export:
      Name: VarLogMessagesBucket
  VarLogMessagesBucketName:
    Description: A reference to the VarLogMessagesBucket Name
    Value: !Ref VarLogMessagesBucket
    Export:
      Name: VarLogMessagesBucketName
  
      