Parameters:
  CloudTrailLogGroupName: 
    Description: Cloud Trail Log Group Name
    Type: String
    Default: "/aws/cloudtrail"
  CloudTrailLogGroupRetention: 
    Description: Cloud Trail Log Group Retention
    Type: Number
    Default: 365
  CloudWatchAgentLogGroupName: 
    Description: CloudWatch Log Group Name
    Type: String
    Default: "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
  CloudWatchAgentLogGroupRetention: 
    Description: CloudWatch Log Group Retention
    Type: Number
    Default: 365
  HTTPAccessLogGroupName: 
    Description: HTTP Access Log Group Name
    Type: String
    Default: "/var/log/httpd/access_log"
  HTTPAccessLogGroupRetention: 
    Description: HTTP Access Log Group Retention
    Type: Number
    Default: 365
  CodeDeployAgentLogGroupName: 
    Description: CodeDeploy Log Group Name
    Type: String
    Default: "/var/log/aws/codedeploy-agent/codedeploy-agent.log"
  CodeDeployAgentLogGroupRetention: 
    Description: CodeDeploy Log Group Retention
    Type: Number
    Default: 365
  ECSAgentLogGroupName: 
    Description: ECSAgent Log Group Name
    Type: String
    Default: "/var/log/ecs/ecs-agent.log"
  ECSAgentLogGroupRetention: 
    Description: ECSAgent Log Group Retention
    Type: Number
    Default: 365
  KinesisAgentLogGroupName: 
    Description: Kinesis Agent Log Group Name
    Type: String
    Default: "/var/log/aws-kinesis-agent/aws-kinesis-agent.log"
  KinesisAgentLogGroupRetention: 
    Description: Kinesis Agent Log Group Retention
    Type: Number
    Default: 365
  ECSTasksLogGroupName: 
    Description: ECSTasks Log Group Name
    Type: String
    Default: "/aws/ecs/tasks"
  ECSTasksLogGroupRetention: 
    Description: ECSTasks Log Group Retention
    Type: Number
    Default: 365
  DeliveryStreamLogGroupName: 
    Description: CloudTrail Delivery Stream Log Group Name
    Type: String
    Default: "/aws/kinesis"
  DeliveryStreamLogGroupRetention: 
    Description: CloudTrail Delivery Stream Log Group Retention
    Type: Number
    Default: 365
  CloudTrailDeliveryStreamLogStreamName: 
    Description: CloudTrail Delivery Stream Log Stream Name
    Type: String 
    Default: "/aws/cloudtrail_backup"
  CloudTrailDeliveryStreamBackupLogStreamName: 
    Description: CloudTrail Delivery Stream Backup Log Stream Name
    Type: String 
    Default: "/aws/cloudtrail"
  VarLogMessagesDeliveryStreamLogStreamName: 
    Description: VarLogMessages Delivery Stream Log Stream Name
    Type: String 
    Default: "/var/log/messages"

    

Resources: 
  CloudTrailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref CloudTrailLogGroupName
      RetentionInDays: !Ref CloudTrailLogGroupRetention
  CloudWatchAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref CloudWatchAgentLogGroupName
      RetentionInDays: !Ref CloudWatchAgentLogGroupRetention
  HTTPAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref HTTPAccessLogGroupName
      RetentionInDays: !Ref HTTPAccessLogGroupRetention
  CodeDeployAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref CodeDeployAgentLogGroupName
      RetentionInDays: !Ref CodeDeployAgentLogGroupRetention
  ECSAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref ECSAgentLogGroupName
      RetentionInDays: !Ref ECSAgentLogGroupRetention
  KinesisAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref KinesisAgentLogGroupName
      RetentionInDays: !Ref KinesisAgentLogGroupRetention
  ECSTasksLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref ECSTasksLogGroupName
      RetentionInDays: !Ref ECSTasksLogGroupRetention
  
  DeliveryStreamLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref DeliveryStreamLogGroupName
      RetentionInDays: !Ref DeliveryStreamLogGroupRetention
  CloudTrailDeliveryStreamLogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref DeliveryStreamLogGroup
      LogStreamName: !Ref CloudTrailDeliveryStreamLogStreamName
  CloudTrailDeliveryStreamBackupLogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref DeliveryStreamLogGroup
      LogStreamName: !Ref CloudTrailDeliveryStreamBackupLogStreamName
  VarLogMessagesDeliveryStreamLogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref DeliveryStreamLogGroup
      LogStreamName: !Ref VarLogMessagesDeliveryStreamLogStreamName

      

Outputs:
  CloudTrailLogGroupName:
    Description: A reference to the CloudTrail Log Group Name
    Value: !Ref CloudTrailLogGroupName
    Export:
      Name: CloudTrailLogGroupName
  CloudTrailLogGroup:
    Description: A reference to the CloudTrail Log Group Arn
    Value: !GetAtt CloudTrailLogGroup.Arn
    Export:
      Name: CloudTrailLogGroup
  CloudWatchAgentLogGroupName:
    Description: A reference to the CloudWatchAgent Log Group Name
    Value: !Ref CloudWatchAgentLogGroupName
    Export:
      Name: CloudWatchAgentLogGroupName
  HTTPAccessLogGroupName:
    Description: A reference to the HTTP Access Log Group Name
    Value: !Ref HTTPAccessLogGroupName
    Export:
      Name: HTTPAccessLogGroupName
  CodeDeployAgentLogGroupName:
    Description: A reference to the CodeDeploy Agent Log Group Name
    Value: !Ref CodeDeployAgentLogGroupName
    Export:
      Name: CodeDeployAgentLogGroupName
  ECSAgentLogGroupName:
    Description: A reference to the ECSAgent Log Group Name
    Value: !Ref ECSAgentLogGroupName
    Export:
      Name: ECSAgentLogGroupName
  KinesisAgentLogGroupName:
    Description: A reference to the KinesisAgent Log Group Name
    Value: !Ref KinesisAgentLogGroupName
    Export:
      Name: KinesisAgentLogGroupName
  ECSTasksLogGroup:
    Description: A reference to the ECSTasks Log Group
    Value: !Ref ECSTasksLogGroup
    Export:
      Name: ECSTasksLogGroup
  ECSTasksLogGroupName:
    Description: A reference to the ECSTasks Log Group Name
    Value: !Ref ECSTasksLogGroupName
    Export:
      Name: ECSTasksLogGroupName

  DeliveryStreamLogGroupName:
    Description: A reference to the DeliveryStream Log Group Name
    Value: !Ref DeliveryStreamLogGroupName
    Export:
      Name: DeliveryStreamLogGroupName
  CloudTrailDeliveryStreamLogStreamName:
    Description: A reference to the CloudTrail Delivery Stream Log Stream Name
    Value: !Ref CloudTrailDeliveryStreamLogStreamName
    Export:
      Name: CloudTrailDeliveryStreamLogStreamName
  CloudTrailDeliveryStreamBackupLogStreamName:
    Description: A reference to the CloudTrail Delivery Stream Backup Log Stream Name
    Value: !Ref CloudTrailDeliveryStreamBackupLogStreamName
    Export:
      Name: CloudTrailDeliveryStreamBackupLogStreamName
  VarLogMessagesDeliveryStreamLogStreamName:
    Description: A reference to the VarLogMessages Delivery Stream Log Stream Name
    Value: !Ref VarLogMessagesDeliveryStreamLogStreamName
    Export:
      Name: VarLogMessagesDeliveryStreamLogStreamName


