Parameters:
  CloudTrailDataStreamName:
    Description: CloudTrail Data Stream Name
    Type: String
    Default: "CloudTrailDataStream"
  CloudTrailDeliveryStreamName:
    Description: CloudTrail Delivery Stream Name
    Type: String
    Default: "CloudTrailDeliveryStream"

Resources:
  CloudTrailDataStream:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: !Ref CloudTrailDataStreamName
      RetentionPeriodHours: 24
      ShardCount: 1

  CloudTrailDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties: 
      DeliveryStreamName: !Ref CloudTrailDeliveryStreamName
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration: 
        KinesisStreamARN: !GetAtt CloudTrailDataStream.Arn
        RoleARN: !ImportValue CloudTrailDeliveryStreamRole
      S3DestinationConfiguration: 
        BucketARN: !ImportValue CloudTrailBucket
        CloudWatchLoggingOptions: 
          Enabled: True
          LogGroupName: !ImportValue DeliveryStreamLogGroupName
          LogStreamName: !ImportValue CloudTrailDeliveryStreamLogStreamName
        CompressionFormat: UNCOMPRESSED
        EncryptionConfiguration:
          NoEncryptionConfig: NoEncryption
        ErrorOutputPrefix: "Kinesis_ERROR"
        RoleARN: !ImportValue CloudTrailDeliveryStreamRole

Outputs:
  CloudTrailDataStream:
    Description: A reference to the CloudTrail Data Stream Arn
    Value: !GetAtt CloudTrailDataStream.Arn
    Export:
      Name: CloudTrailDataStream
      
