Parameters:
  KeyPair:
    Description: KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    Default: "AWS_KeyPair"
  PublicSubnet:
    Description: Choose the Public Subnets the Bastion Host will be deployed in
    Type: AWS::EC2::Subnet::Id

Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0f19d220602031aed"
      InstanceType: t2.micro
      KeyName: !Ref KeyPair
      NetworkInterfaces: 
      - DeviceIndex: "0"
        GroupSet: 
          - !ImportValue EC2SecurityGroup
        SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: BastionHost

Outputs:
  BastionHostIP:
    Description: A reference to the Bastion Host IP
    Value: !GetAtt BastionHost.PublicIp