Parameters:
  TrailName: 
    Description: Cloud Trail Name
    Type: String
    Default: CloudTrail
  CloudTrailBucketName:
    Description: Bucket Name for Cloud Trail Logs
    Type: String

Resources:
  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties: 
      CloudWatchLogsLogGroupArn: !ImportValue CloudTrailLogGroup
      CloudWatchLogsRoleArn: !ImportValue CloudTrailRole
      EnableLogFileValidation: No
      EventSelectors: 
        - IncludeManagementEvents: True
          ReadWriteType: All
      IncludeGlobalServiceEvents: True
      IsLogging: Yes
      S3BucketName: !Ref CloudTrailBucketName
      TrailName: !Ref TrailName
