Resources:
  CloudWatchLogsSubscription:
    Type: AWS::Logs::SubscriptionFilter
    Properties: 
      DestinationArn: !ImportValue CloudTrailDataStream
      FilterPattern: " "
      LogGroupName: !ImportValue CloudTrailLogGroupName
      RoleArn: !ImportValue CloudWatchToKinesisRole
