Parameters:
  KeyPair:
    Description: KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    Default: "AWS_KeyPair"
  PublicSubnet:
    Description: Choose the Public Subnets the Bastion Host will be deployed in
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - c1.medium
      - c1.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c3.large
      - c3.xlarge
      - cc2.8xlarge
      - cg1.4xlarge
      - cr1.8xlarge
      - g2.2xlarge
      - hi1.4xlarge
      - hs1.8xlarge
      - i2.2xlarge
      - i2.4xlarge
      - i2.8xlarge
      - i2.xlarge
      - m1.large
      - m1.medium
      - m1.small
      - m1.xlarge
      - m2.2xlarge
      - m2.4xlarge
      - m2.xlarge
      - m3.2xlarge
      - m3.large
      - m3.medium
      - m3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - r3.large
      - r3.xlarge
      - t1.micro
      - t2.medium
      - t2.micro
      - t2.small
    Description: Instance Type

Mappings:
  AmznLinux2AMIRegionMap:
    ap-northeast-1:
      AMIID: ami-02d36247c5bc58c23
    ap-northeast-2:
      AMIID: ami-04e8dfc09b22389ad
    ap-northeast-3:
      AMIID: ami-026107638e7d599b1
    ap-south-1:
      AMIID: ami-041db4a969fe3eb68
    ap-southeast-1:
      AMIID: ami-07191cf2912e097a6
    ap-southeast-2:
      AMIID: ami-04a81599b183d7908
    ca-central-1:
      AMIID: ami-0d8ad3ab25e7abc51
    eu-central-1:
      AMIID: ami-047e03b8591f2d48a
    eu-north-1:
      AMIID: ami-001c5f3c0a8b3f245
    eu-west-1:
      AMIID: ami-0ed961fa828560210
    eu-west-2:
      AMIID: ami-074771aa49ab046e7
    eu-west-3:
      AMIID: ami-0da7ba92c3c072475
    sa-east-1:
      AMIID: ami-07983613af1a3ef44
    us-east-1:
      AMIID: ami-01cc34ab2709337aa
    us-east-2:
      AMIID: ami-0f19d220602031aed
    us-west-1:
      AMIID: ami-0e0bf4b3a0c0e0adc
    us-west-2:
      AMIID: ami-0e5b6b6a9f3db6db8

Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AmznLinux2AMIRegionMap, !Ref "AWS::Region", AMIID]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      NetworkInterfaces: 
      - DeviceIndex: "0"
        GroupSet: 
          - !ImportValue EC2SecurityGroup
        SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: BastionHost
        - Key: AllowInspector
          Value: Enabled

Outputs:
  BastionHostIP:
    Description: A reference to the Bastion Host IP
    Value: !GetAtt BastionHost.PublicIp